version: '3'
services:
    postgres:
        image: 'postgres:latest'
        env_file: ./.env
    redis:
        image: 'redis:latest'
        env_file: ./.env
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
