version: '3'
services:
    chtabotbackend:
        build:
            dockerfile: Dockerfile
            context: ./server
    postgres:
        image: 'postgres:latest'
        env_file: ./.env
    redis:
        image: 'redis:latest'
        env_file: ./.env
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '8080:80'
